apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  namespace: blog
spec:
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: fine-quail-balanced.ngrok-free.app/minhyoyo/blog-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog
spec:
  type: LoadBalancer
  selector:
    app: blog-app
  ports:
  - port: 80
    targetPort: 80

